name: Application pull request

jobs:
  install-yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable

  eslint:
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn application:eslint

  install-cypress:
    needs: install-yarn
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
    strategy:
      matrix:
        os: [ubuntu, windows]

  module:
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build module
        run: yarn module:rollup
      - name: Upload module
        uses: actions/upload-artifact@v2
        with:
          name: module--dist
          path: packages/module/dist

  build:
    needs: module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module--dist
          path: packages/module/dist
      - name: Build
        run: yarn application:build
        env:
          REACT_APP_VERSION: ${{ github.sha }}
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: application--build
          path: packages/application/build

  cypress:
    needs: [install-cypress, module]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module--dist
          path: packages/module/dist
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: End-to-end test
        uses: cypress-io/github-action@v2
        env:
          CHOKIDAR_USEPOLLING: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYC_REPORT_DIR: cypress/coverage/${{ matrix.os }}-${{ matrix.browser }}-${{ matrix.container }}
          REACT_VERSION: ${{ github.sha }}
        with:
          browser: ${{ matrix.browser }}
          ci-build-id: ${{ github.event_name }}-${{ github.sha }}
          command-prefix: yarn dlx
          group: ${{ matrix.os }}-${{ matrix.browser }}
          # We install during the Setup Node step so that we may use a
          #   Node-dependent `start` command.
          # install-command: yarn install --immutable
          parallel: true
          project: packages/application
          record: true
          start: yarn application:cypress:start
          tag: ${{ github.event_name }}
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: application--cypress-coverage
          path: packages/application/cypress/coverage
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: application--cypress-screenshots
          path: packages/application/cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v2
        with:
          name: application--cypress-videos
          path: packages/application/cypress/videos
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        browser: [edge, firefox, chrome]
        container: [1]
        exclude:
          - browser: edge
            os: ubuntu

  jest:
    needs: module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module--dist
          path: packages/module/dist
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Unit test
        run: yarn application:jest
        env:
          DD_ENV: ci
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: application--jest-coverage
          path: packages/application/jest/coverage

  coverage:
    needs: [cypress, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Download Cypress coverage
        uses: actions/download-artifact@v2
        with:
          name: application--cypress-coverage
          path: packages/application/cypress/coverage
      - name: Download Jest coverage
        uses: actions/download-artifact@v2
        with:
          name: application--jest-coverage
          path: packages/application/jest/coverage
      - name: Report coverage
        run: yarn application:coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: application--coverage
          path: packages/application/coverage

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/application-pull-request.yml'
      - 'packages/application/**/*'
      - 'packages/module/**/*'
