name: Application push

jobs:
  install-yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install

  eslint:
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn application:eslint

  install-cypress:
    needs: install-yarn
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
    strategy:
      matrix:
        os: [ubuntu, windows]

  module:
    needs: install-yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Build module
        run: yarn module:rollup
      - name: Upload module
        uses: actions/upload-artifact@v2
        with:
          name: module-rollup
          path: packages/module/dist

  build:
    needs: module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module-rollup
          path: packages/module/dist
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn application:build
        env:
          REACT_APP_VERSION: ${{ github.sha }}
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: application-build
          path: packages/application/build

  cypress:
    needs: [install-cypress, module]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module-rollup
          path: packages/module/dist
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: End-to-end test
        uses: cypress-io/github-action@v2
        env:
          CHOKIDAR_USEPOLLING: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYC_REPORT_DIR: cypress/coverage/${{ matrix.os }}-${{ matrix.browser }}-${{ matrix.container }}
          REACT_APP_VERSION: ${{ github.sha }}
        with:
          browser: ${{ matrix.browser }}
          ci-build-id: ${{ github.event_name }}-${{ github.sha }}
          command-prefix: yarn dlx
          group: ${{ matrix.os }}-${{ matrix.browser }}
          # We install during the Setup Node step so that we may use a
          #   Node-dependent `start` command.
          # install-command: yarn install
          parallel: true
          project: packages/application
          record: true
          start: yarn application:cypress:start
          tag: ${{ github.event_name }}
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: application-cypress-coverage
          path: packages/application/cypress/coverage
    strategy:
      fail-fast: false
      matrix:
        # Skip Windows while cypress-io/github-action doesn't support it.
        # https://github.com/cypress-io/github-action/issues/459
        os: [ubuntu] # , windows
        browser: [edge, firefox, chrome]
        container: [1]
        exclude:
          - browser: edge
            os: ubuntu

  jest:
    needs: module
    runs-on: ubuntu-latest
    # services:
    #   datadog-agent:
    #     image: datadog/agent:latest
    #     env:
    #       DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    #       DD_HOSTNAME: none
    #       DD_INSIDE_CI: true
    #     ports:
    #       - 8126:8126
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module-rollup
          path: packages/module/dist
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Unit test
        run: yarn application:jest
        env:
          DD_ENV: ci
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: application-jest-coverage
          path: packages/application/jest/coverage

  github-pages:
    needs: [build, cypress, eslint, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: application-build
          path: packages/application/build
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          clean: true
          folder: packages/application/build
          single-commit: true

  sentry-release:
    needs: [build, cypress, eslint, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: application-build
          path: packages/application/build
      - name: Release Sentry version
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: info
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_VERSION: ${{ github.sha }}
        with:
          environment: production
          sourcemaps: packages/application/build
          version: ${{ env.SENTRY_VERSION }}

  # cloudflare-purge:
  #   needs: github-pages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         cache: yarn
  #         check-latest: true
  #         node-version: 'lts/*'
  #     - name: Install dependencies
  #       run: yarn install
  #     - name: Purge Cloudflare cache
  #       env:
  #         CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  #       run: >
  #         curl \
  #           --data '{
  #             "files": [
  #               "https://charlesstover.com",
  #               "https://charlesstover.com/index.html"
  #             ]
  #           }' \
  #           --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  #           --header "Content-Type:application/json" \
  #           --request POST \
  #           "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache"

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/application-push.yml'
      - 'packages/application/**/*'
      - 'packages/module/**/*'
