name: Module pull request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 14 # 'lts/*'
      - name: Install dependencies
        run: yarn install

  eslint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 14 # 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn module:eslint

  jest:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 14 # 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Unit test
        run: yarn module:jest
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: module-jest-coverage
          path: packages/module/jest/coverage

  rollup:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 14 # 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn module:rollup
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: module-rollup
          path: packages/module/dist

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/module-pull-request.yml'
      - 'packages/module/**/*'
