name: Module

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable

  eslint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn module:eslint

  jest:
    needs: install
    runs-on: ubuntu-latest
    # services:
    #   datadog-agent:
    #     image: datadog/agent:latest
    #     env:
    #       DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    #       DD_HOSTNAME: none
    #       DD_INSIDE_CI: true
    #     ports:
    #       - 8126:8126
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Unit test
        run: yarn module:jest
      - name: Upload coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: module--jest--coverage
          path: packages/module/jest/coverage

  rollup:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn module:rollup
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: module--dist
          path: packages/module/dist

  # github:
  #   if: ${{ github.event_name == 'push' }}
  #   needs: [eslint, jest, rollup]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         cache: yarn
  #         check-latest: true
  #         node-version: 'lts/*'
  #         registry-url: 'https://npm.pkg.github.com/'
  #         scope: '@${{ github.repository_owner }}'
  #     - name: Install dependencies
  #       run: yarn install --immutable
  #     - name: Download build
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: module--dist
  #         path: packages/module/dist
  #     - name: Change scope
  #       env:
  #         REPOSITORY_OWNER: ${{ github.repository_owner }}
  #       run: yarn module:change-scope
  #     - name: Publish
  #       working-directory: packages/module
  #       env:
  #         NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: >
  #         yarn config set npmAuthToken $NPM_AUTH_TOKEN;
  #         yarn npm publish --tolerate-republish;

  npm:
    if: ${{ github.event_name == 'push' }}
    needs: [eslint, jest, rollup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: module--dist
          path: packages/module/dist
      - name: Publish
        working-directory: packages/module
        run: >
          yarn config set npmAuthToken $NPM_AUTH_TOKEN;
          yarn npm publish --tolerate-republish;
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/module.yml'
      - 'packages/jest-preset/**/*'
      - 'packages/jest-transformer/**/*'
      - 'packages/module/**/*'
  push:
    branches: [main]
    paths:
      - '.github/workflows/module.yml'
      - 'packages/jest-preset/**/*'
      - 'packages/jest-transformer/**/*'
      - 'packages/module/**/*'
